In [19]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import _cm
import numpy as np
import pandas as pd
import plotly.graph_objects as go

## MLE como base para la regrsion logistica

- estamos trabajando con la distribucion de bernoulli

In [20]:
def likelihood(y,yp):
    return yp*y+(1-y)*(1-yp)

In [21]:
y=np.arange(0,1,0.01)
yp=np.arange(0,1,0.01)
Y,YP =np.meshgrid(y,yp) #Construye una cuadricula
Z = likelihood(Y,YP)


In [22]:
fig = go.Figure(data=[go.Surface(z=Z, x=Y, y=YP)])
fig.show()

In [23]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
values=['sepal length','sepal width','petal length','petal width']
# Values en X y Etiquetas en Y para el modelo
X, y = load_iris(return_X_y=True)



- Reduciendo la muestra, para volverlo un modelo de clasificacion binario

In [24]:
X[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [25]:
y[:2]

array([0, 0])

## Aqui estan los parametros betas, para las cuatro variables del dataset de iris

In [18]:
clasificacion_linear_model=LogisticRegression(random_state=10, solver='liblinear').fit(X[:100],y[:100])
clasificacion_linear_model.coef_


array([[-0.40247392, -1.46382925,  2.23785648,  1.00009294]])